pipeline:
  build:
    image: node:carbon
    commands:
      - npm install
      - npm run test

  notify:
    image: agatticelli/drone-hangouts-chat:1.0.7
    room_id: AAAAS5FvlIQ
    key: AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI
    token: CiqvAgIuurr276UHaFbReNQgkX7aAO1ynDDAckEIOgY%3D
