pipeline:
  build:
    image: node:carbon
    commands:
      - npm install
      - npm run test

  notify:
    image: agatticelli/drone-hangouts-chat:1.0.7
    room_id: AAAArpurF-o
    key: AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI
    token: n_GX_P0TpiNu7Ka6XkLl7OJIJRN9xuTjzT1KB7fExKU%3D