pipeline:
  build:
    image: node:carbon
    commands:
      - npm install
      - npm run test

  notify:
    image: agatticelli/drone-hangouts-chat:latest
    roomId: AAAANThTpic
    key: AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI
    token: 0Y6X4o2q5gRebPrT65B-khFTJiwI3vAzjw9ewMoCuLA%3D
